# <meta>
#    <source>@pssbletrngle/github-meta-generator</source>
#    <version>1.0.116</version>
#    <timestamp>2026-07-30T07:58:37.892Z</timestamp>
#    <hash>b3cb79442b758887</hash>
# </meta>

name: Release
on:
  workflow_dispatch:

  push:
    branches:
      - "main"
      - "main/**"
    paths:
      - "**.java"
      - "**.kt"
      - "gradle.properties"
      - "gradle/**"

env:
  CI: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: write
      packages: read
    steps:
      - uses: actions/checkout@v7
        with:
          lfs: true

      - uses: actions/setup-java@v5
        with:
          java-version: 26
          distribution: temurin

      - uses: gradle/actions/setup-gradle@v6
        with:
          cache-read-only: ${{ github.event_name != 'push' }}

      - name: Build and upload
        run: ./gradlew build upload
        env:
          CHANGELOG: automated patch release
          PATCH_VERSION: ${{ github.run_number }}
          NEXUS_USER: ${{ secrets.NEXUS_USER }}
          NEXUS_TOKEN: ${{ secrets.NEXUS_TOKEN }}

      - name: Publish Release Metadata
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: build/release.json
          retention-days: 1

      - name: Create tag
        uses: PssbleTrngle/create-tag@v1
        with:
          from: build/release.json
          token: ${{ secrets.GITHUB_TOKEN }}
