# <meta>
#    <source>@pssbletrngle/github-meta-generator</source>
#    <version>1.0.93</version>
#    <timestamp>2026-06-17T16:44:32.635Z</timestamp>
#    <hash>2a2a64e30fe8cb30</hash>
# </meta>

name: Test

on:
  workflow_dispatch:

  pull_request:
    types: [opened, synchronize]

  push:
    branches:
      - "main"
      - "main/**"

env:
  CI: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v5
        with:
          java-version: 26
          distribution: temurin

      - uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: ${{ github.event_name != 'push' }}
          dependency-graph: generate-and-submit

      - name: Test
        run: ./gradlew build check --stacktrace
